- name: Configure SSL
  hosts: webservers
  become: yes
  tasks:
    - name: Install mod_ssl
      yum:
        name: mod_ssl
        state: present

    - name: Create self-signed certificate
      command: openssl req -new -newkey rsa:2048 -days 365 -nodes -x509 -subj "/C=US/ST=State/L=City/O=Organization/OU=Department/CN=example.com" -keyout /etc/pki/tls/private/localhost.key -out /etc/pki/tls/certs/localhost.crt

    - name: Configure Apache for SSL
      copy:
        content: |
          <VirtualHost *:80>
            ServerName example.com
            Redirect / https://example.com/
          </VirtualHost>

          <VirtualHost *:443>
            ServerName example.com
            DocumentRoot /var/www/html
            SSLEngine on
            SSLCertificateFile /etc/pki/tls/certs/localhost.crt
            SSLCertificateKeyFile /etc/pki/tls/private/localhost.key
          </VirtualHost>
        dest: /etc/httpd/conf.d/ssl.conf
