- name: Configure HTTPS
  hosts: web
  become: yes
  tasks:
    - name: Install OpenSSL
      apt:
        name: openssl
        state: present

    - name: Create self-signed certificate
      command: openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/nginx/selfsigned.key -out /etc/nginx/selfsigned.crt -subj "/CN=localhost"

    - name: Configure Nginx for HTTPS
      copy:
        content: |
          server {
              listen 80;
              server_name localhost;
              return 301 https://$host$request_uri;
          }

          server {
              listen 443 ssl;
              server_name localhost;

              ssl_certificate /etc/nginx/selfsigned.crt;
              ssl_certificate_key /etc/nginx/selfsigned.key;

              location / {
                  root /var/www/html;
                  index index.html;
              }
          }
        dest: /etc/nginx/sites-available/default
        owner: root
        group: root
        mode: 0644

    - name: Restart Nginx
      service:
        name: nginx
        state: restarted
